export const common = {
'的':{pinyin:'de',english:'(possessive particle), of / really and truly / aim, clear',code: 30340,audio: require('/home/bb/Code/trinity/client/assets/chars/common/30340.mp3')},
'一':{pinyin:'yī / yì ／yí',english:'one / single / a(n)',code: 19968,audio: require('/home/bb/Code/trinity/client/assets/chars/common/19968.mp3')},
'是':{pinyin:'shì',english:'is, are, am, yes to be',code: 26159,audio: require('/home/bb/Code/trinity/client/assets/chars/common/26159.mp3')},
'不':{pinyin:'bù',english:'(negative prefix) no, not',code: 19981,audio: require('/home/bb/Code/trinity/client/assets/chars/common/19981.mp3')},
'了':{pinyin:'le／liǎo',english:'(modal particle intensifying preceding clause), (past tense marker) / to know, to understand, to know',code: 20102,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20102.mp3')},
'人':{pinyin:'rén',english:'man, person, people',code: 20154,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20154.mp3')},
'我':{pinyin:'wǒ',english:'I, me, myself',code: 25105,audio: require('/home/bb/Code/trinity/client/assets/chars/common/25105.mp3')},
'在':{pinyin:'zài',english:'(located) at, in, exist',code: 22312,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22312.mp3')},
'有':{pinyin:'yǒu',english:'to have, there is, there are, to exist, to be',code: 26377,audio: require('/home/bb/Code/trinity/client/assets/chars/common/26377.mp3')},
'他':{pinyin:'tā',english:'he, him',code: 20182,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20182.mp3')},
'这':{pinyin:'zhè',english:'this/ these',code: 36825,audio: require('/home/bb/Code/trinity/client/assets/chars/common/36825.mp3')},
'为':{pinyin:'wéi / wèi',english:'act as, take…to be, to be, to do, to serve as, to become / because of, for, to',code: 20026,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20026.mp3')},
'之':{pinyin:'zhī',english:'him, her, it',code: 20043,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20043.mp3')},
'大':{pinyin:'dà',english:'big, huge, large, major, great, wide, deep, oldest, eldest / doctor',code: 22823,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22823.mp3')},
'来':{pinyin:'lái',english:'to come',code: 26469,audio: require('/home/bb/Code/trinity/client/assets/chars/common/26469.mp3')},
'以':{pinyin:'yǐ',english:'to use, take, according to, because of, in order to',code: 20197,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20197.mp3')},
'个':{pinyin:'gè',english:'(a measure word), individual',code: 20010,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20010.mp3')},
'中':{pinyin:'zhōng',english:'within, among, in, middle, center, while (doing something), during',code: 20013,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20013.mp3')},
'上':{pinyin:'shàng',english:'above, on, over, top, (go) up, last, previous',code: 19978,audio: require('/home/bb/Code/trinity/client/assets/chars/common/19978.mp3')},
'们':{pinyin:'men',english:'(plural marker for pronouns and a few animate nouns)',code: 20204,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20204.mp3')},
'到':{pinyin:'dào',english:'to (a place), until (a time), up to, to go, to arrive',code: 21040,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21040.mp3')},
'说':{pinyin:'shuō',english:'to speak, to say',code: 35828,audio: require('/home/bb/Code/trinity/client/assets/chars/common/35828.mp3')},
'国':{pinyin:'guó',english:'country, state, nation',code: 22269,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22269.mp3')},
'和':{pinyin:'hé / huò',english:'and, together, with, peace / harmony',code: 21644,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21644.mp3')},
'地':{pinyin:'de / dì',english:'-ly / earth, ground, field, place, land',code: 22320,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22320.mp3')},
'也':{pinyin:'yě',english:'too, also, as well',code: 20063,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20063.mp3')},
'子':{pinyin:'zǐ',english:'child, son',code: 23376,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23376.mp3')},
'时':{pinyin:'shí',english:'time, when, hour, period, season',code: 26102,audio: require('/home/bb/Code/trinity/client/assets/chars/common/26102.mp3')},
'道':{pinyin:'dào',english:'direction, way, method, road, path, principle, truth, reason, skill, method, Tao (of Taoism), a measure word, to say, to speak, to talk',code: 36947,audio: require('/home/bb/Code/trinity/client/assets/chars/common/36947.mp3')},
'出':{pinyin:'chū',english:'to go out, to come out, to occur, to produce, to go beyond, to rise, to put forth, to occur, to happen',code: 20986,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20986.mp3')},
'而':{pinyin:'ér',english:'and, as well as, but (not), yet (not), (shows causal relation), (shows change of state), (shows contrast)',code: 32780,audio: require('/home/bb/Code/trinity/client/assets/chars/common/32780.mp3')},
'要':{pinyin:'yào / yāo',english:'vital, to want, to be going to, must / demand, ask, request',code: 35201,audio: require('/home/bb/Code/trinity/client/assets/chars/common/35201.mp3')},
'于':{pinyin:'yú',english:'at, in, in regard to',code: 20110,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20110.mp3')},
'就':{pinyin:'jiù',english:'at once, then, right away, only, just',code: 23601,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23601.mp3')},
'下':{pinyin:'xià',english:'below, under, (go) down, next (as opposed to previous/last)',code: 19979,audio: require('/home/bb/Code/trinity/client/assets/chars/common/19979.mp3')},
'得':{pinyin:'dé / de / děi',english:'obtain, get, gain, to have to, must, ought to, to need to',code: 24471,audio: require('/home/bb/Code/trinity/client/assets/chars/common/24471.mp3')},
'可':{pinyin:'kě',english:'can, may, able to, certain(ly), (particle used for emphasis)',code: 21487,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21487.mp3')},
'你':{pinyin:'nǐ',english:'you',code: 20320,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20320.mp3')},
'年':{pinyin:'nián',english:'year',code: 24180,audio: require('/home/bb/Code/trinity/client/assets/chars/common/24180.mp3')},
'生':{pinyin:'shēng',english:'to be born, to give birth, life, to grow',code: 29983,audio: require('/home/bb/Code/trinity/client/assets/chars/common/29983.mp3')},
'自':{pinyin:'zì',english:'from, self, oneself, since',code: 33258,audio: require('/home/bb/Code/trinity/client/assets/chars/common/33258.mp3')},
'会':{pinyin:'huì',english:'can, able, meet, meeting, society, union, party',code: 20250,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20250.mp3')},
'那':{pinyin:'nà',english:'that, those',code: 37027,audio: require('/home/bb/Code/trinity/client/assets/chars/common/37027.mp3')},
'后':{pinyin:'hòu',english:'back, behind, rear, afterwards, after, later',code: 21518,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21518.mp3')},
'能':{pinyin:'néng',english:'can, may, capable, energy, able',code: 33021,audio: require('/home/bb/Code/trinity/client/assets/chars/common/33021.mp3')},
'对':{pinyin:'duì',english:'couple, pair, to be opposite, to oppose, to face, for, to, correct (answer), to answer, to reply, to direct (towards something), right',code: 23545,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23545.mp3')},
'着':{pinyin:'zhe／zhuó／zhāo／zháo',english:'verb particle marking a continuing progress/state',code: 30528,audio: require('/home/bb/Code/trinity/client/assets/chars/common/30528.mp3')},
'事':{pinyin:'shì',english:'matter, thing, item, work, affair',code: 20107,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20107.mp3')},
'其':{pinyin:'qí',english:'his, her, its, theirs, that, such, it (refers to something preceding it)',code: 20854,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20854.mp3')},
'里':{pinyin:'lǐ',english:'within, inside',code: 37324,audio: require('/home/bb/Code/trinity/client/assets/chars/common/37324.mp3')},
'所':{pinyin:'suǒ',english:'actually，place',code: 25152,audio: require('/home/bb/Code/trinity/client/assets/chars/common/25152.mp3')},
'去':{pinyin:'qù',english:'to go, to leave, to depart',code: 21435,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21435.mp3')},
'行':{pinyin:'háng / xíng',english:'a row, profession, professional / all right, capable, competent, okay, to go, to do, to travel, temporary, to walk, to go, will do / behavior, conduct',code: 34892,audio: require('/home/bb/Code/trinity/client/assets/chars/common/34892.mp3')},
'过':{pinyin:'guò',english:'(past tense marker), to cross, to go over, to pass (time), to live, to get along, (surname)',code: 36807,audio: require('/home/bb/Code/trinity/client/assets/chars/common/36807.mp3')},
'家':{pinyin:'jiā',english:'home, family, a person engaged in a certain art or profession',code: 23478,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23478.mp3')},
'十':{pinyin:'shí',english:'ten',code: 21313,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21313.mp3')},
'用':{pinyin:'yòng',english:'to use',code: 29992,audio: require('/home/bb/Code/trinity/client/assets/chars/common/29992.mp3')},
'发':{pinyin:'fā／fà',english:'to send out, to show (one‘s feeling), to issue, to develop / hair',code: 21457,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21457.mp3')},
'天':{pinyin:'tiān',english:'day, sky, heaven',code: 22825,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22825.mp3')},
'如':{pinyin:'rú',english:'as (if), such as',code: 22914,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22914.mp3')},
'然':{pinyin:'rán',english:'correct, right, so, thus, like this, -ly',code: 28982,audio: require('/home/bb/Code/trinity/client/assets/chars/common/28982.mp3')},
'作':{pinyin:'zuò',english:'to regard as, to take (somebody) for, to do, to make',code: 20316,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20316.mp3')},
'方':{pinyin:'fāng',english:'square, quadrilateral, direction, just',code: 26041,audio: require('/home/bb/Code/trinity/client/assets/chars/common/26041.mp3')},
'成':{pinyin:'chéng',english:'finish, complete, accomplish, become, turn into, win, succeed',code: 25104,audio: require('/home/bb/Code/trinity/client/assets/chars/common/25104.mp3')},
'者':{pinyin:'zhě',english:'-ist, -er (person), person (who does something)',code: 32773,audio: require('/home/bb/Code/trinity/client/assets/chars/common/32773.mp3')},
'多':{pinyin:'duō',english:'many, much, a lot of, numerous, multi-',code: 22810,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22810.mp3')},
'日':{pinyin:'rì',english:'day, sun, date, day of the month',code: 26085,audio: require('/home/bb/Code/trinity/client/assets/chars/common/26085.mp3')},
'都':{pinyin:'dōu',english:'all, both (if two things are involved), entirely (due to)each, even, already',code: 37117,audio: require('/home/bb/Code/trinity/client/assets/chars/common/37117.mp3')},
'三':{pinyin:'sān',english:'three',code: 19977,audio: require('/home/bb/Code/trinity/client/assets/chars/common/19977.mp3')},
'小':{pinyin:'xiǎo',english:'small, tiny, few, young',code: 23567,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23567.mp3')},
'军':{pinyin:'jūn',english:'army, military, arms',code: 20891,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20891.mp3')},
'二':{pinyin:'èr',english:'two',code: 20108,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20108.mp3')},
'无':{pinyin:'wú',english:'-less, not to have, no, none, not, to lack, un-',code: 26080,audio: require('/home/bb/Code/trinity/client/assets/chars/common/26080.mp3')},
'同':{pinyin:'tóng',english:'like, same, similar, together, alike, with',code: 21516,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21516.mp3')},
'么':{pinyin:'me',english:'(interrog. suff.)',code: 20040,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20040.mp3')},
'经':{pinyin:'jīng',english:'classics, sacred book, pass through, to undergo, scripture',code: 32463,audio: require('/home/bb/Code/trinity/client/assets/chars/common/32463.mp3')},
'法':{pinyin:'fǎ',english:'law, method, way, Buddhist teaching',code: 27861,audio: require('/home/bb/Code/trinity/client/assets/chars/common/27861.mp3')},
'当':{pinyin:'dāng / dàng',english:'to be, to act as, manage, withstand, when, during, ought, should, match equally, equal, same, obstruct, just at (a time or place), on the spot, right, just at / at or in the very same…, to pawn, suitable, adequate, fitting, proper, replace, represent',code: 24403,audio: require('/home/bb/Code/trinity/client/assets/chars/common/24403.mp3')},
'起':{pinyin:'qǐ',english:'qǐ：to rise, to raise, to get up',code: 36215,audio: require('/home/bb/Code/trinity/client/assets/chars/common/36215.mp3')},
'与':{pinyin:'yú / yǔ / yù',english:'(interrog. part.) / and, to give, together with / take part in',code: 19982,audio: require('/home/bb/Code/trinity/client/assets/chars/common/19982.mp3')},
'好':{pinyin:'hǎo / hào',english:'good, well / be fond of',code: 22909,audio: require('/home/bb/Code/trinity/client/assets/chars/common/22909.mp3')},
'看':{pinyin:'kān / kàn',english:'to look after, to take care of, to watch, to guard / it depends, think, to see, to look at',code: 30475,audio: require('/home/bb/Code/trinity/client/assets/chars/common/30475.mp3')},
'学':{pinyin:'xué',english:'learn, study, science, -ology',code: 23398,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23398.mp3')},
'进':{pinyin:'jìn',english:'advance, enter, to come in',code: 36827,audio: require('/home/bb/Code/trinity/client/assets/chars/common/36827.mp3')},
'种':{pinyin:'zhǒng / zhòng',english:'kind, type, race (of people), seed, type / to grow, to plant',code: 31181,audio: require('/home/bb/Code/trinity/client/assets/chars/common/31181.mp3')},
'将':{pinyin:'jiāng / jiàng',english:'(will, shall, future tense), ready, prepared, to get, to use / a general',code: 23558,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23558.mp3')},
'还':{pinyin:'hái / huán',english:'also, in addition, more, still, else, still, yet, (not) yet / (surname), pay back, return',code: 36824,audio: require('/home/bb/Code/trinity/client/assets/chars/common/36824.mp3')},
'分':{pinyin:'fēn / fèn',english:'to divide, minute, (a measure word), (a unit of length = 0.33centimeter) / part',code: 20998,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20998.mp3')},
'此':{pinyin:'cǐ',english:'this, these',code: 27492,audio: require('/home/bb/Code/trinity/client/assets/chars/common/27492.mp3')},
'心':{pinyin:'xīn',english:'heart, mind',code: 24515,audio: require('/home/bb/Code/trinity/client/assets/chars/common/24515.mp3')},
'前':{pinyin:'qián',english:'before, in front, ago, former, previous, earlier, front',code: 21069,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21069.mp3')},
'面':{pinyin:'miàn',english:'face, side, surface, aspect, top, face, flour, noodles',code: 38754,audio: require('/home/bb/Code/trinity/client/assets/chars/common/38754.mp3')},
'又':{pinyin:'yòu',english:'(once) again, also, both… and…, again',code: 21448,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21448.mp3')},
'定':{pinyin:'dìng',english:'to set, to fix, to determine, to decide, to order',code: 23450,audio: require('/home/bb/Code/trinity/client/assets/chars/common/23450.mp3')},
'见':{pinyin:'jiàn / xiàn',english:'to see, to meet, to appear (to be something), to interview / appear',code: 35265,audio: require('/home/bb/Code/trinity/client/assets/chars/common/35265.mp3')},
'只':{pinyin:'zhī／zhǐ',english:'only, just, but, measure word for one of a pair',code: 21482,audio: require('/home/bb/Code/trinity/client/assets/chars/common/21482.mp3')},
'主':{pinyin:'zhǔ',english:'to own, to host, master, lord, primary',code: 20027,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20027.mp3')},
'没':{pinyin:'méi／mò',english:'(negative prefix for verbs), have not, not / sink, disappear',code: 27809,audio: require('/home/bb/Code/trinity/client/assets/chars/common/27809.mp3')},
'公':{pinyin:'gōng',english:'just, honorable (designation), public, common',code: 20844,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20844.mp3')},
'从':{pinyin:'cóng',english:'from, since, obey, observe, follow',code: 20174,audio: require('/home/bb/Code/trinity/client/assets/chars/common/20174.mp3')},
};

